Allow CUDA 12.6
I was just setting up a new computer, and it looks like I had the bad luck to do it right after a CUDA minor version bump.

```
error: failed to run custom build command for `cudarc v0.11.6`

Caused by:
  process didn't exit successfully: `/home/paul/.cargo/target/debug/build/cudarc-74c0b2ca7b5abc3a/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-env-changed=CUDA_ROOT
  cargo:rerun-if-env-changed=CUDA_PATH
  cargo:rerun-if-env-changed=CUDA_TOOLKIT_ROOT_DIR

  --- stderr
  thread 'main' panicked at /home/paul/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cudarc-0.11.6/build.rs:79:14:
  Unsupported cuda toolkit version: `12.6`. Please raise a github issue.
```

When I tested this locally, I got a bunch of compile errors in `cudarc`, but I assume that's just some unrelated bit of setup I need to figure out.