driver/safe test: fix 20% relative tolerance instead of absolute
The LHS has units of ms, but the RHS looks like it may have been
intended to be 20% rather than an absolute tolerance of 0.2 ms. Without
this change, I get test failures like this:

thread 'driver::safe::launch::tests::test_par_launch' panicked at src/driver/safe/launch.rs:670:9:
par=147.41606 dbl=295.22842